##########
## DESC:    Describes the docker container.  Run docker-compose ... to use the configuration
##          specified in this document.
## NOTES:   Regarding USB access see:
##            - README.md section
##            - https://stackoverflow.com/a/53892718/11940985
## AUTHOR:  Silas Waxter (silaswaxter@gmail.com)
## DATE:    05/06/2022
###########
services:
  anvil:
    image: anvil:latest
    build: .
    volumes:
      - type: bind
        source: /dev/bus/usb
        target: /dev/bus/usb
        read_only: true
    device_cgroup_rules:
      - 'c 189:* rwm'
